import { AlertTriangle, LoaderCircle, Plus, RefreshCw, Search, X } from 'lucide-react';
import { formatMoney } from '../constants';
export function PageHeader({ title, description, actions }) { return <div className="bcrm-page-head"><div><p className="bcrm-eyebrow">Gen Z Business Console</p><h1>{title}</h1>{description && <p>{description}</p>}</div>{actions && <div className="bcrm-actions">{actions}</div>}</div>; }
export function Button({ children, variant = 'primary', icon: Icon, ...props }) { return <button className={`bcrm-btn bcrm-btn-${variant}`} {...props}>{Icon && <Icon size={16} />}{children}</button>; }
export function AddButton({ children = 'Add new', ...props }) { return <Button icon={Plus} {...props}>{children}</Button>; }
export function Card({ title, subtitle, actions, children, className = '' }) { return <section className={`bcrm-card ${className}`}><header className="bcrm-card-head"><div>{title && <h2>{title}</h2>}{subtitle && <p>{subtitle}</p>}</div>{actions}</header><div className="bcrm-card-body">{children}</div></section>; }
export function Metric({ label, value, hint, tone = 'blue', currency }) { return <article className={`bcrm-metric bcrm-tone-${tone}`}><span className="bcrm-metric-mark"/><p>{label}</p><strong>{currency ? formatMoney(value, currency) : value}</strong>{hint && <small>{hint}</small>}</article>; }
export function Loading({ label = 'Loading business data…' }) { return <div className="bcrm-state"><LoaderCircle className="bcrm-spin" size={30}/><strong>{label}</strong></div>; }
export function ErrorState({ message, onRetry }) { return <div className="bcrm-state bcrm-state-error"><AlertTriangle size={30}/><strong>Could not load this workspace</strong><p>{message}</p>{onRetry && <Button variant="secondary" icon={RefreshCw} onClick={onRetry}>Try again</Button>}</div>; }
export function Empty({ title = 'No records yet', description = 'Create the first record to begin.' }) { return <div className="bcrm-empty"><strong>{title}</strong><p>{description}</p></div>; }
export function Table({ columns, rows, rowKey = 'id', empty, onRow, className = '' }) { if (!rows?.length) return <Empty {...empty}/>; return <div className={`bcrm-table-wrap ${className}`.trim()}><table className="bcrm-table"><thead><tr>{columns.map((column) => <th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row[rowKey] || index} onClick={onRow ? () => onRow(row) : undefined} className={onRow ? 'is-clickable' : ''}>{columns.map((column) => <td key={column.key} data-label={column.label}>{column.render ? column.render(row) : row[column.key] ?? '—'}</td>)}</tr>)}</tbody></table></div>; }
export function Field({ label, hint, className = '', children }) { return <label className={`bcrm-field ${className}`}><span>{label}</span>{children}{hint && <small>{hint}</small>}</label>; }
export function Input(props) { return <input className="bcrm-input" {...props}/>; }
export function Select(props) { return <select className="bcrm-input" {...props}/>; }
export function Textarea(props) { return <textarea className="bcrm-input bcrm-textarea" {...props}/>; }
export function Status({ children, tone = 'neutral', className = '' }) { return <span className={`bcrm-status bcrm-status-${tone} ${className}`.trim()}>{children}</span>; }
export function SearchBox({ value, onChange, placeholder = 'Search…' }) { return <label className="bcrm-search"><Search size={16}/><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder}/>{value && <button type="button" onClick={() => onChange('')} aria-label="Clear search"><X size={14}/></button>}</label>; }
export function Modal({ open, title, children, onClose, footer }) { if (!open) return null; return <div className="bcrm-modal-backdrop" role="presentation" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><section className="bcrm-modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button onClick={onClose} aria-label="Close"><X size={19}/></button></header><div className="bcrm-modal-body">{children}</div>{footer && <footer>{footer}</footer>}</section></div>; }
