import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Plus, Save } from 'lucide-react';
import { crmApi, messageFromError } from '../api';
import { useDebouncedValue, useResource } from '../hooks';
import { useBusinessCrm } from '../BusinessCrmContext';
import { queueOperation } from '../offline/queue';
import { AddButton, Button, Card, ErrorState, Field, Input, Loading, Modal, PageHeader, SearchBox, Status, Table, Textarea } from '../components/ui';
const blank={name:'',whatsapp:'',email:'',company:'',address:'',taxId:'',notes:'',status:'active'};
export default function Contacts({kind}){const crm=useBusinessCrm();const label=kind==='clients'?'Clients':'Vendors';const singular=kind==='clients'?'client':'vendor';const nav=useNavigate();const[q,setQ]=useState('');const[modal,setModal]=useState(false);const[form,setForm]=useState(blank);const[error,setError]=useState('');const[saving,setSaving]=useState(false);const dq=useDebouncedValue(q);const r=useResource(()=>`/contacts/${kind}?pageSize=100&q=${encodeURIComponent(dq)}`,[kind,dq]);const save=async()=>{setSaving(true);setError('');try{if(!navigator.onLine){await queueOperation(kind==='clients'?'client.create':'vendor.create',form,crm.bootstrap?.user?.id);crm.setQueued(crm.queued+1);setModal(false);setForm(blank);setError(`${singular} queued and will appear after synchronization.`);return;}await crmApi.post(`/contacts/${kind}`,form);setModal(false);setForm(blank);r.reload()}catch(e){setError(messageFromError(e))}finally{setSaving(false)}};if(r.initialLoading)return <Loading/>;if(r.error)return <ErrorState message={r.error} onRetry={r.reload}/>;return <><PageHeader title={label} description={kind==='clients'?'Customer profiles, purchase history, collections and follow-ups.':'Supplier profiles, purchasing history, dues and payment ledgers.'} actions={<AddButton onClick={()=>setModal(true)}>Add {singular}</AddButton>}/><div className="bcrm-filterbar"><SearchBox value={q} onChange={setQ} busy={r.loading} placeholder={`Name, phone, email or company…`}/></div><Card className="flush" title={`${r.data?.total||0} ${label.toLowerCase()}`}><Table rows={r.data?.rows||[]} onRow={x=>nav(x.id)} columns={[{key:'name',label:'Name'},{key:'company',label:'Company'},{key:'whatsapp',label:'WhatsApp'},{key:'email',label:'Email'},{key:'status',label:'Status',render:x=><Status tone={x.status==='active'?'success':'neutral'}>{x.status}</Status>}]} /></Card><Modal open={modal} title={`Add ${singular}`} onClose={()=>setModal(false)} footer={<><Button variant="secondary" onClick={()=>setModal(false)}>Cancel</Button><Button icon={Save} onClick={save} disabled={saving}>{saving?'Saving…':'Save'}</Button></>}>{error&&<div className="bcrm-banner warning">{error}</div>}<div className="bcrm-form-grid"><Field label="Name"><Input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="WhatsApp"><Input value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/></Field><Field label="Email"><Input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Company"><Input value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/></Field><Field label="Address" className="full"><Textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></Field><Field label="Notes"><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div></Modal></>}
