import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Download, Plus, RefreshCw } from 'lucide-react';
import { useBusinessCrm } from '../BusinessCrmContext';
import { useDebouncedValue, useResource } from '../hooks';
import { crmApi } from '../api';
import { formatDate, formatMoney } from '../constants';
import { Button, Card, ErrorState, Field, Loading, PageHeader, SearchBox, Select, Status, Table } from '../components/ui';
export default function Sales(){const crm=useBusinessCrm();const nav=useNavigate();const[q,setQ]=useState('');const[status,setStatus]=useState('');const dq=useDebouncedValue(q);const path=()=>`/sales?currency=${crm.currency}&q=${encodeURIComponent(dq)}&status=${status}`;const r=useResource(path,[crm.currency,dq,status]);if(r.initialLoading)return <Loading/>;if(r.error)return <ErrorState message={r.error} onRetry={r.reload}/>;return <><PageHeader title="Sales & invoices" description="Editable transaction history with protected payment ledgers and PDF invoices." actions={<>{crm.has('exports.download')&&<Button variant="secondary" icon={Download} onClick={()=>window.open(crmApi.rawUrl('/admin/exports/sales.csv'),'_blank','noopener,noreferrer')}>Export CSV</Button>}{crm.has('sales.create')&&<Button icon={Plus} onClick={()=>nav('new')}>New sale</Button>}</>}/><div className="bcrm-filterbar"><Field label="Status"><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="open">Open</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></Select></Field><SearchBox value={q} onChange={setQ} busy={r.loading} placeholder="Invoice, client or product…"/><Button variant="secondary" icon={RefreshCw} onClick={r.reload}>Refresh</Button></div><Card className="flush" title={`${r.data?.total||0} sale records`} subtitle={`All values remain separate in ${crm.currency}`}><Table rows={r.data?.rows||[]} onRow={row=>nav(row.id)} columns={[{key:'invoice_number',label:'Invoice'},{key:'sale_date',label:'Date',render:x=>formatDate(x.sale_date)},{key:'client_name',label:'Client'},{key:'item_names',label:'Products'},{key:'subtotal_sale',label:'Sale',render:x=>formatMoney(x.subtotal_sale,x.currency_code)},{key:'client_pending',label:'Pending',render:x=>formatMoney(x.client_pending,x.currency_code)},{key:'status',label:'Status',render:x=><Status tone={x.status==='completed'?'success':x.status==='cancelled'?'danger':'warning'}>{x.status}</Status>}]} /></Card></>}
